---
name: Module-Mask
version: 0.03
author:
  - 'Matt Lawrence <mattlaw@cpan.org>'
abstract: Pretend certain modules are not installed
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Module::Util: 1.00
  Scalar::Util: 1.01
  perl: 5.8.0
build_requires:
  Test::More: 0
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
provides:
  Module::Mask:
    file: lib/Module/Mask.pm
    version: 0.03
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
